language: node_js
node_js:
- "14"
- node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: test
      node_js: node
      script: jest
    - stage: Produce Coverage
      node_js: node
      script: jest && codecov
